name: Debug Playground

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the rpi_image_creation branch
  push:
    branches: [ rpi_image_creation ]
  pull_request:
    branches: [ rpi_image_creation]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    # TODO: I don't think this step is needed....
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - name: Checkout RaSCSI
#        uses: actions/checkout@v2
#        with:
#          path: RASCSI
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout RaSCSI
        uses: actions/checkout@v2
        with:
          repository: akuker/pi-gen
          path: pi-gen
      
#      - name: Install Raspberry Pi build toolchain
#        run: sudo apt-get install coreutils quilt parted qemu-user-static debootstrap zerofree zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc qemu-utils kpartx

      - name: Configure the build
        run: |
          echo -----------------------------------------------------
          echo "IMG_NAME=RaSCSI-$GITHUB_RUN_ID" > config
          echo "TARGET_HOSTNAME=rascsi" >> config
          echo "ENABLE_SSH=1" >> config
          echo "LOCALE_DEFAULT=en_US.UTF-8" >> config
          echo "KEYBOARD_KEYMAP=us" >> config
          echo "KEYBOARD_LAYOUT=\"English (US)\"" >> config
          echo -----------------------------------------------------
          cat config
          echo Github Run ID: $GITHUB_RUN_ID
          echo Github Run Number: $GITHUB_RUN_NUMBER
          echo Github Event Path: $GITHUB_EVENT_PATH
          echo Github Repository: $GITHUB_REPOSITORY
          echo Github Event Path: $GITHUB_EVENT_PATH
          echo Github Base Ref: $GITHUB_BASE_REF
          echo Github Head Ref: $GITHUB_HEAD_REF
          echo Github Ref: $GITHUB_REF
          echo Github Ref: $GITHUB_REF
          echo Github Ref: $GITHUB_REF
          echo Github CI: $CI
          if [ "$CI" = "true" ]; then
            echo "Strings are equal."
          else
            echo "Strings are not equal."
          fi
          echo ("${CI}" == true)
          echo ("${CI}" != true)
          echo Full URL: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
        working-directory: pi-gen
